---
- hosts: all
  become: yes
  tasks:
  -  name: Install redis on RedHat Family
     yum:
        name=redis
        state=latest
     when:
        ansible_os_family == "RedHat"
     notify:
        redis systemd
  -  name: Install redis on Ubuntu
     apt:
        name=redis
        state=latest
     when:
        ansible_os_family == "Debian"
     notify:
        redis systemd
  handlers:
  - name: redis systemd
    systemd:
     name: redis.service
     enabled: yes
     state: started